version: '3.8'
services:
  web:
    depends_on:
      - mongo
    build: .
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - .:/app
    ports:
      - 8081:8081
  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-jwt:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo-jwt:
